#!/bin/bash

repositorio="$1"

touch .gitignore
echo "node_modules" > .gitignore

gh repo create "alura-$repositorio" --private
sleep 5
git init
git add .
git commit -m "Subindo projeto da alura"
git branch -M main
git remote add origin "https://github.com/guiffsouza/alura-$repositorio.git"
git push origin main